name = "modfest-skyandsea"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a59a4a048281bec89aaeddca2c51d2d21eaf542045ffb4d4876698e2b6a8328d"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
